### ISSUE TITLE
findmex utility segfaults during call to analysegeom()

### ISSUE THREAD

**Issue by cthree-40** [virtualzx-nad/surfgen#14]
To print out the final geometry, findmex calls analysegeom.
After printing out the final geometry, printing bond distances results in a segmentation fault.
The segmentation fault is caused by TLen (input variable of analysegeom) having no value during the analysegeom call.

Possible fixes: set TLen in findmex, or test if TLen has been set in analysegeom; if not, set it.

**Comment by virtualzx-nad** [comment]
The problem has been fixed as suggested.
